function m(b,a,c,d){b.m.qb(b.ub,a,c,d)}function n(b,a,c,d){b.m.ba?m(b,a,c,d):b.m.Ve()._OnMessageFromDOM({type:"event",component:b.ub,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.m.B(b.ub,a,c)}function aa(b,a){for(const [c,d]of a)q(b,c,d)}function v(b){b.Zb||(b.m.Ec(b.ke),b.Zb=!0)}window.Ob=class{constructor(b,a){this.m=b;this.ub=a;this.Zb=!1;this.ke=()=>this.Ta()}sd(){}Ta(){}};
window.Gf=class{constructor(){this.nd=-1}j(){-1!==this.nd&&(self.clearTimeout(this.nd),this.nd=-1)}};"use strict";class ba{constructor(b){this.xb=b;this.Uc=!1;this.ad=!0;this.zb=this.ra=this.od=-1}}
function ca(b,a){const c=a.elementId,d=b.Pa(c,a),e=new ba(d);b.La.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.ad=!!a.isVisible;var f=b.Hc(d);f.addEventListener("focus",()=>{w(b,"elem-focused",c)});f.addEventListener("blur",()=>{w(b,"elem-blurred",c)});f=a.htmlIndex;e.od=f;e.zb=a.htmlZIndex;b.Wa&&(a=b.m.vc(f),e.ra=a,b.m.Pb(a).appendChild(d))}function x(b,a,c){q(b,a,d=>{const e=y(b,d.elementId);return c(e,d)})}
function y(b,a){b=b.La.get(a);if(!b)throw Error(`no element with id ${a}`);return b.xb}function w(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}function z(b,a,c){c||(c={});c.elementId=a;n(b,"click",c)}
window.Ea=class extends self.Ob{constructor(b,a){super(b,a);this.La=new Map;this.Wa=!0;aa(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=y(this,c);this.xd(d);this.Wa&&d.parentElement.removeChild(d);this.La.delete(c)}],["set-visible",c=>{if(this.Wa){var d=this.La.get(c.elementId),e=d.xb;d.Uc?e.style.display=c.isVisible?"":"none":d.ad=!!c.isVisible}}],["update-position",c=>{if(this.Wa){var d=this.La.get(c.elementId),e=d.xb,f=this.m;e.style.left=c.left+"px";e.style.top=c.top+"px";
e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.od=g;g=f.vc(g);g!==d.ra&&(e.remove(),f.Pb(g).appendChild(e),d.ra=g,f.Oc());c=c.htmlZIndex;c!==d.zb&&(d.zb=c,f.Oc());d.Uc||(d.Uc=!0,d.ad&&(e.style.display=""))}}],["update-state",c=>{const d=y(this,c.elementId);this.ga(d,c)}],["focus",c=>{const d=this.Hc(y(this,c.elementId));c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=y(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?
d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{y(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{y(this,c.elementId).removeAttribute(c.name)}]]);x(this,"get-element",c=>c)}Pa(){throw Error("required override");}xd(){}ga(){throw Error("required override");}Hc(b){return b}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),ea=/android/i.test(navigator.userAgent),ha=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ia=0;function ja(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.wf?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.Af+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ka(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const la={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ma(b){b=await na(b);return(new TextDecoder("utf-8")).decode(b)}
function na(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const oa=[];let B=0;window.RealFile=window.File;const C=[],qa=new Map,ra=new Map;let va=0;const wa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");wa.push(b)};const xa=new Set(["cordova","playable-ad","instant-games"]);let ya=!1;
window.pa=class b{constructor(a){this.ba=a.Cf;this.Aa=null;this.aa="";this.gb=a.zf;this.Mb={};this.$a=this.wa=null;this.Ya=[];this.na=null;this.Yd=!0;this.M=[];this.gd=[];this.hd=!1;this.le=()=>this.Te();this.Yc=!1;this.Sd=0;this.Bb=null;this.fb=-1;this.sf=()=>this.df();this.Jb=new Set;this.pd=null;this.me=[];this.A=a.ne;this.ac="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.ba=!1;ha&&(this.ba=!1);if("cordova"===this.A&&this.ba&&ea){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.Ra()?self.chrome.webview.addEventListener("message",c=>this.Hd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Hd(c));this.dc=this.ta=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.hf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Ze());this.B("runtime","cordova-fetch-local-file",c=>this.$e(c));this.B("runtime","create-job-worker",()=>this.af());this.B("runtime","send-wrapper-extension-message",c=>this.gf(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Fd(a)):this.Fd(a)}j(){this.Fc();this.Aa&&(this.Aa=this.Aa.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.$a&&(this.$a.j(),this.$a=null);for(const {canvas:a,
jb:c}of this.M)a.remove(),c.remove();this.M.length=0}Fe(){return this.M[0].canvas}vc(a){return Math.min(a,this.M.length-1)}Pb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].jb}Je(){return da&&"cordova"===this.A}ob(){const a=navigator.userAgent;return da&&xa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}He(){return ea}yd(){return ea&&xa.has(this.A)}Ad(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Ra(){return this.Ad()||"xbox-uwp-webview2"===this.A}async Fd(a){this.ba&&!await ka()&&(this.ba=!1);"macos-wkwebview"===this.A?this.rb({type:"ready"}):this.Ra()&&(this.kf(),this.me=(await this.Ye()).registeredComponentIds);if("playable-ad"===this.A){this.ta=self.c3_base64files;this.dc={};await this.Qe();for(let d=0,e=a.ib.length;d<e;++d){var c=a.ib[d];this.dc.hasOwnProperty(c)?a.ib[d]={wf:!0,Af:this.dc[c]}:this.ta.hasOwnProperty(c)&&(a.ib[d]=URL.createObjectURL(this.ta[c]))}a.sc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Ec(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.yf?this.aa=a.yf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Ef&&(this.Mb=a.Ef);c=new MessageChannel;this.Aa=c.port1;this.Aa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.cf(d));this.Bb=
new self.Ke(this);await za(this.Bb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.Xe(a,c.port2):await this.We(a,c.port2)}Ic(a){a=this.Mb.hasOwnProperty(a)?this.Mb[a]:a.endsWith("/workermain.js")&&this.Mb.hasOwnProperty("workermain.js")?this.Mb["workermain.js"]:"playable-ad"===
this.A&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async uc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.ac)return a=await this.Nb(d.vf?a:this.gb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}qa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}xc(){return this.Ra()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.A)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Ed(a){var c=this.aa,d=location.href,e=this.qa(),f=this.ha(),g=this.xc(),
h=window.devicePixelRatio,k=b.nb(),l=a.Jf,p=window.cr_previewImageBlobs||this.ta,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.ne;var fa=(new URLSearchParams(self.location.search)).has("debug"),K=this.Bb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:p,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,exportType:a,isDebug:fa,
ife:!!self.If,jobScheduler:{inputPort:K.Xc,outputPort:K.fd,maxNumWorkers:K.pf},supportedAudioFormats:la,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.gb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.gb+"opus.wasm.wasm",isFileProtocol:this.ac,isiOSCordova:this.Je(),isiOSWebView:this.ob(),isWindowsWebView2:this.Ad(),isAnyWebView2Wrapper:this.Ra(),wrapperComponentIds:this.me,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Xe(a,c){const d=this.Ic(a.Df);"preview"===
this.A?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.wa.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.wa.addEventListener("message",r);this.wa.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.wa=await this.uc(d,this.aa,{type:"module",name:"Runtime",vf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);
const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,jb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.sc||[],k=a.ib;h=await Promise.all(h.map(l=>this.Ua(l)));k=await Promise.all(k.map(l=>this.Ua(l)));if("cordova"===this.A)for(let l=0,p=a.rc.length;l<p;++l){const r=a.rc[l],t=r[0];if(t===a.qd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ua(t)}this.wa.postMessage(Object.assign(this.Ed(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.rc,mainProjectScript:a.qd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...Aa(this.Bb)]);this.Ya=C.map(l=>new l(this));this.Dd();Ba(e);Ca(g);Da(this.na);self.c3_callFunction=(l,p)=>{var r=this.na;return r.m.Bd(r.ub,"js-invoke-function",{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.qb("runtime","go-to-last-error-script"))}async We(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,jb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ya=C.map(h=>new h(this));this.Dd();Ba(d);Ca(e);e=a.ib.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.sc)){var f=[...a.sc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Ua(h)));await Promise.all(e.map(h=>ja(h)));e=self.C3_ProjectScriptsStatus;f=a.qd;const g=a.rc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ua(k),await ja(k),"preview"!==this.A||e[h]||this.Jd(h,"main script did not run to completion")}catch(l){this.Jd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Ua(k),await ja(k);"preview"===this.A&&"object"!==typeof self.Ff.Hf?(this.Ub(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ed(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:wa}),Da(this.na),this.Gd(),this.$a=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.$a,a))}Jd(a,c){this.Ub();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Gd(){this.Ub()}Ub(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async af(){const a=await Fa(this.Bb);return{outputPort:a,transferables:[a]}}hf(a){if(!this.Yc){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,jb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Yd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Yd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,jb:p}=this.M.pop();p.remove();this.ba&&!d?this.gd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,Ba(c),Ca(d),this.M.push({canvas:c,jb:d});for(const l of this.Ya)if(l instanceof window.Ea&&l.Wa)for(const p of l.La.values())e=l.m.vc(p.od),f=p.ra,-1!==
e&&-1!==f&&e!==f&&(f=p.xb,f.remove(),l.m.Pb(e).appendChild(f),p.ra=e);this.Oc();return{addedCanvases:a,transferables:k}}Ze(){for(const a of this.gd)a.remove();this.gd.length=0}Oc(){this.hd||(this.hd=!0,this.Ec(this.le))}Te(){this.Id(this.le);this.hd=!1;let a=[];for(var c of this.Ya)if(c instanceof window.Ea){var d=c.Wa?[...c.La.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.ra,l=h.ra;return k!==l?k-l:g.zb-h.zb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.ra!==c&&(this.Cd(c,a.slice(d,
e)),c=g.ra,d=e)}d<e&&this.Cd(c,a.slice(d,e))}Cd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.xb);var d=new Set(c);a=this.Pb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Ve(){if(this.ba)throw Error("not available in worker mode");return this.$a}qb(a,c,d,e,f){this.Aa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Bd(a,c,d,e,f){const g=va++,h=new Promise((k,l)=>{ra.set(g,{resolve:k,reject:l})});this.Aa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.bf(a);if("result"===c)this.ef(a);else if("runtime-ready"===c)this.ff();else if("alert-error"===c)this.Ub(),alert(a.message);else if("creating-runtime"===c)this.Gd();else throw Error(`unknown message '${c}'`);}bf(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=qa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Tb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Tb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Tb(f,!1,""+h)}):this.Tb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Tb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.Aa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}ef(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ra.get(c);d?e.resolve(a):e.reject(a);ra.delete(c)}B(a,c,d){let e=qa.get(a);e||(e=new Map,qa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static xa(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}Dd(){for(const a of this.Ya)if("runtime"===a.ub){this.na=a;return}throw Error("cannot find runtime DOM handler");
}cf(a){this.qb("debugger","message",a)}ff(){for(const a of this.Ya)a.sd()}static nb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ya)}static Kd(a){ya=!!a}Ec(a){this.Jb.add(a);this.Nc()}Id(a){this.Jb.delete(a);0===this.Jb.size&&this.Fc()}Nc(){-1===this.fb&&0<this.Jb.size&&(this.fb=requestAnimationFrame(this.sf))}Fc(){-1!==this.fb&&(cancelAnimationFrame(this.fb),this.fb=-1)}df(){this.fb=-1;for(const a of this.Jb)a();this.Nc()}Ha(a){this.na.Ha(a)}Sa(a){this.na.Sa(a)}Mc(){this.na.Mc()}Sb(a){this.na.Sb(a)}Ie(){return!!la["audio/webm; codecs=opus"]}async lf(a){a=
await this.Bd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Me(a){this.Yc=!0;this.Sd=a}Ge(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}zd(a){return!this.Ge(a)}async Ua(a){return"cordova"===this.A&&(a.startsWith("file:")||this.ac&&this.zd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Nb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async $e(a){const c=a.filename;switch(a.as){case "text":return await this.Ee(c);
case "buffer":return await this.Nb(c);default:throw Error("unsupported type");}}vd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ee(a){a=await this.vd(a);return await ma(a)}Gc(){if(oa.length&&!(8<=B)){B++;var a=oa.shift();this.Re(a.filename,a.Bf,a.uf)}}Nb(a){return new Promise((c,d)=>{oa.push({filename:a,Bf:e=>{B--;this.Gc();c(e)},uf:e=>{B--;this.Gc();d(e)}});this.Gc()})}async Re(a,c,d){try{const e=
await this.vd(a),f=await na(e);c(f)}catch(e){d(e)}}Hd(a){if("entered-fullscreen"===a)b.Kd(!0),E(this.na);else if("exited-fullscreen"===a)b.Kd(!1),E(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.pd(a),this.pd=null):"extension-message"===c?this.qb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}gf(a){this.rb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,
params:a.params||[],asyncId:a.asyncId})}rb(a){this.Ra()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}kf(){window.moveTo=(a,c)=>{this.rb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.rb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ye(){return this.Ra()?new Promise(a=>{this.pd=a;this.rb({type:"wrapper-init"})}):
Promise.resolve()}async Qe(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.Pe(c,d));await Promise.all(a)}async Pe(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.dc[a]=c.str;else{let d=await this.Ue(c);d||(d=this.Se(c));this.ta[a]=d}}async Ue(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Se(a){a=this.jf(a);return this.Oe(a.data,a.xf)}jf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{xf:a,data:d}}Oe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const F=self.pa,Ga=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),G={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ha={dispatchUserScriptEvent:!0},Ia={dispatchRuntimeEvent:!0};function Ja(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Ka(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function La(b){b=URL.createObjectURL(b);try{return await Ka(b)}finally{URL.revokeObjectURL(b)}}function Ma(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Na=new Set(["input","textarea","datalist","select"]),Oa=new Set(["canvas","body","html"]);
function H(b){b.target.tagName&&Oa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Pa(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Qa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await La(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await La(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ra=!1;document.addEventListener("pause",()=>Ra=!0);document.addEventListener("resume",()=>Ra=!1);function Ba(b){b.addEventListener("selectstart",H);b.addEventListener("gesturehold",H);b.addEventListener("pointerdown",H)}function Ca(b){b.addEventListener("selectstart",Pa);b.addEventListener("gesturehold",Pa);b.addEventListener("touchstart",Pa)}function Da(b){b.Rd=!0;b.bd=b.m.qa();b.Cb=b.m.ha()}
function E(b){if(!b.la){var a=F.nb();a&&"any"!==b.ld&&Sa(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ha()})}}async function Ta(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ua(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Va(b){return await self.C3_GetSvgImageSize(b.blob)}function Wa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Xa(b){self.setTimeout(()=>{b.Qd=!0},1E3);"cordova"===b.m.A?(document.addEventListener("pause",()=>Ya(b,!0)),document.addEventListener("resume",()=>Ya(b,!1))):document.addEventListener("visibilitychange",()=>Ya(b,"hidden"===document.visibilityState));b.ic=!("hidden"!==document.visibilityState&&!Ra);return{isSuspended:b.ic}}
function Za(b){b.Md||(b.Md=!0,window.addEventListener("deviceorientation",a=>{b.la||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},G)}),window.addEventListener("deviceorientationabsolute",a=>{b.la||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},G)}))}
function $a(b){b.Ld||(b.Ld=!0,window.addEventListener("devicemotion",a=>{if(!b.la){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},G)}}))}async function ab(b){await Ja(b.url)}
function bb(b,a){b.Td=a.message;-1===b.Sc&&(b.Sc=setTimeout(()=>{b.Sc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Td)},250))}function cb(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:F.nb(),innerWidth:b.qa(),innerHeight:b.ha()})}
function Ya(b,a){b.ic!==a&&((b.ic=a)?b.m.Fc():b.m.Nc(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.ob()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function db(b,a,c){"Backspace"===c.key&&H(c);"nwjs"===b.m.A&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.la){var d=Ga.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},G)}}
function I(b,a,c,d){b.la||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Da,pageX:c.pageX,pageY:c.pageY+b.Da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function J(b,a,c){if(!b.la){var d=0;"mouse"===c.pointerType&&(d=b.dd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Da,pageX:c.pageX,pageY:c.pageY+b.Da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},G);"mouse"===c.pointerType&&
(b.dd=c.buttons)}}function eb(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Da=a))}}
function fb(b,a,c,d){const e=b.qa(),f=b.ha();b.hb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.nb(),cssDisplayMode:b.m.xc()}):10>d&&gb(b,e,f,d+1)}function gb(b,a,c,d){-1!==b.hb&&clearTimeout(b.hb);b.hb=setTimeout(()=>fb(b,a,c,d),48)}
function Sa(b){b=b.ld;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function hb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
F.xa(class extends self.Ob{constructor(b){super(b,"runtime");this.Rd=!1;this.hb=-1;this.ld="any";this.ic=this.Ld=this.Md=!1;this.oc=document.createElement("div");this.oc.className="c3-screen-reader-text";this.oc.setAttribute("aria-live","polite");document.body.appendChild(this.oc);this.Ka=null;this.la=!1;this.Td="";this.Sc=-1;this.Qd=!1;this.bd=b.qa();this.Cb=b.ha();this.Da=this.Lb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ta(c));b.B("runtime","raster-svg-image",c=>Ua(c));b.B("runtime","get-svg-image-size",c=>Va(c));b.B("runtime","set-target-orientation",c=>{this.ld=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Wa(c));b.B("runtime","go-to-script",c=>Wa(c));b.B("runtime","before-start-ticking",()=>Xa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ka||(this.Ka=document.createElement("div"),this.Ka.id="inspectOutline",document.body.appendChild(this.Ka));var d=this.Ka;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ka&&(this.Ka.style.display="none")});b.B("runtime","enable-device-orientation",()=>Za(this));b.B("runtime","enable-device-motion",()=>$a(this));b.B("runtime","add-stylesheet",c=>ab(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.oc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.la=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.Fe().style.display="";this.m.Me(c.duration)});b.B("runtime","export-to-video-progress",c=>bb(this,c));b.B("runtime","exported-to-video",c=>{window.tf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.tf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ma(d)||c.preventDefault()});window.addEventListener("selectstart",H);window.addEventListener("gesturehold",H);window.addEventListener("touchstart",H,{passive:!1});window.addEventListener("pointerdown",H,{passive:!1});this.dd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Qa,{passive:!1});window.addEventListener("wheel",Qa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.la&&this.Rd){var c=this.qa();var d=this.ha();if(this.m.yd()){if(this.Qd){if(this.bd===
c&&d<this.Cb){this.Lb=this.Cb-d;eb(this,this.Cb,this.Lb);c=void 0;break a}0<this.Lb&&(this.Lb=0,eb(this,d,this.Lb))}this.bd=c;this.Cb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.nb(),cssDisplayMode:this.m.xc()});this.m.ob()&&(-1!==this.hb&&clearTimeout(this.hb),fb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>E(this));window.addEventListener("webkitfullscreenchange",()=>E(this));window.addEventListener("mozfullscreenchange",
()=>E(this));window.addEventListener("fullscreenerror",c=>cb(this,c));window.addEventListener("webkitfullscreenerror",c=>cb(this,c));window.addEventListener("mozfullscreenerror",c=>cb(this,c));if(b.ob()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.ab=new Set;this.fc=new WeakSet;this.za=!1}sd(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Ia)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Ia);this.dd=0});window.addEventListener("focusin",a=>{a=a.target;(Na.has(a.tagName.toLowerCase())||Ma(a))&&m(this,"keyboard-blur",null,Ia)});window.addEventListener("keydown",a=>db(this,"keydown",a));window.addEventListener("keyup",a=>db(this,"keyup",a));window.addEventListener("mousedown",a=>I(this,"mousedown",a,
Ha));window.addEventListener("mousemove",a=>I(this,"mousemove",a,Ha));window.addEventListener("mouseup",a=>I(this,"mouseup",a,Ha));window.addEventListener("dblclick",a=>I(this,"dblclick",a,G));window.addEventListener("wheel",a=>{this.la||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Da,pageX:a.pageX,pageY:a.pageY+this.Da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},G)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
hb(a.target)&&document.activeElement&&!hb(document.activeElement)&&document.activeElement.blur();J(this,"pointerdown",a)});this.m.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{J(this,"pointermove",a)}):window.addEventListener("pointermove",a=>J(this,"pointermove",a));window.addEventListener("pointerup",a=>J(this,"pointerup",a));window.addEventListener("pointercancel",a=>J(this,"pointercancel",a));const b=()=>this.Mc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.m.He()&&!this.m.yd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{eb(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}));this.m.ob()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.m.qa()}ha(){return this.m.ha()}Mc(){var b=
[...this.ab];this.ab.clear();if(!this.za)for(const a of b)(b=a.play())&&b.catch(()=>{this.fc.has(a)||this.ab.add(a)})}Ha(b){if("function"!==typeof b.play)throw Error("missing play function");this.fc.delete(b);let a;try{a=b.play()}catch(c){this.ab.add(b);return}a&&a.catch(()=>{this.fc.has(b)||this.ab.add(b)})}Sa(b){this.ab.delete(b);this.fc.add(b)}Sb(b){this.za=!!b}});"use strict";
async function za(b){if(b.mf)throw Error("already initialised");b.mf=!0;var a=b.Ba.Ic(("playable-ad"===b.Ba.A?b.Ba.gb:"")+"dispatchworker.js");b.Rc=await b.Ba.uc(a,b.tb,{name:"DispatchWorker"});a=new MessageChannel;b.Xc=a.port1;b.Rc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.fd=await Fa(b)}function Aa(b){return[b.Xc,b.fd]}
async function Fa(b){const a=b.Zd.length;var c=b.Ba.Ic(("playable-ad"===b.Ba.A?b.Ba.gb:"")+"jobworker.js");c=await b.Ba.uc(c,b.tb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Rc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Zd.push(c);return e.port1}
self.Ke=class{constructor(b){this.Ba=b;this.tb=b.aa;this.tb="preview"===b.A?this.tb+"workers/":this.tb+b.gb;this.pf=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.Zd=[];this.fd=this.Xc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.pa({Cf:!0,Df:"workermain.js",ib:["scripts/c3runtime.js"],rc:[],qd:"",zf:"scripts/",sc:[],ne:"html5"}));"use strict";function L(b){b.stopPropagation()}
self.pa.xa(class extends self.Ea{constructor(b){super(b,"button")}Pa(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",L);d.addEventListener("pointermove",
L);d.addEventListener("pointerrawupdate",L);d.addEventListener("pointerup",L);d.addEventListener("mousedown",L);d.addEventListener("mouseup",L);d.addEventListener("keydown",L);d.addEventListener("keyup",L);d.addEventListener("contextmenu",e=>e.preventDefault());c.addEventListener("click",()=>z(this,b,{isChecked:c.checked}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.ga(d,a);return d}Hc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}ga(b,a){const c="input"===b.tagName.toLowerCase()?
b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";async function ib(b,a){a=a.type;let c=!0;0===a?c=await jb():1===a&&(c=await lb());m(b,"permission-result",{type:a,result:c})}
async function jb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function lb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.pa.xa(class extends self.Ob{constructor(b){super(b,"touch");q(this,"request-permission",a=>ib(this,a))}});"use strict";const mb=180/Math.PI;
async function nb(b,a){if(a.isiOSCordova||a.isSafari)b.kc=!0;b.md=a.timeScaleMode;b.de=["equalpower","HRTF","soundfield"][a.panningModel];b.Pd=["linear","inverse","exponential"][a.distanceModel];b.ee=a.refDistance;b.ce=a.maxDistance;b.ge=a.rolloffFactor;if(b.m.Yc)b.kc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Sd)});else{var c={latencyHint:a.latencyHint};b.je||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");ob(b);b.g.onstatechange=()=>{"running"!==b.g.state&&ob(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Xa=b.g.createGain();b.Xa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>M(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function pb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.$d=g.slice(0);qb(b,g);try{b.R=await rb(b,c,d,e,g,f);if(p){N(b.R,!0);var u=b.R,fa=p.x,K=p.y,Hb=p.z,Ib=p.angle,sa=p.innerAngle,ta=p.outerAngle,ua=p.outerGain;if(u.Ab){sb(u,fa,K,Hb,Ib);var D=self.kb.Ne;
u.ua[0]!==D(sa)&&(u.ua[0]=D(sa),u.F.coneInnerAngle=D(sa));u.ua[1]!==D(ta)&&(u.ua[1]=D(ta),u.F.coneOuterAngle=D(ta));u.ua[2]!==ua&&(u.ua[2]=ua,u.F.coneOuterGain=ua)}p.hasOwnProperty("uid")&&(b.R.sa=p.uid)}else"number"===typeof r&&0!==r?(O(b.R,!0),tb(b.R,r)):(N(b.R,!1),O(b.R,!1));b.R.Play(h,k,l,t)}catch(Jb){console.error("[Construct] Audio: error starting playback: ",Jb);return}finally{c=g.join(" ");d=b.Ib.get(c);if(!d)throw Error("expected pending tag");d.rd--;0===d.rd&&(d.resolve(),b.Ib.delete(c))}v(b)}
async function ub(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await vb(b,c);for(const h of P(b,c))if(!h.ya){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Oa=d;h.Za=g;h.ie=a}Q(b)}async function wb(b,a){const c=a.tags;a=a.rate;await vb(b,c);for(const d of P(b,c))d.ma!==a&&(d.ma=a,d.Ia())}async function xb(b,a){const c=a.tags;a=a.pos;await vb(b,c);for(const d of P(b,c))d.Bc(a)}
async function yb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await rb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function zb(b,a){if(a=await M(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function Ab(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await M(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.te(b,...e);else if("delay"===c)d=new self.re(b,...e);else if("convolution"===c){var g=d=new self.qe(b,f.ia,...e),h=a.bufferType;g.Nd=a.bufferOriginalUrl;g.Od=h}else if("flanger"===c)d=
new self.ue(b,...e);else if("phaser"===c)d=new self.we(b,...e);else if("gain"===c)d=new self.ve(b,...e);else if("stereopan"===c)d=new self.ye(b,...e);else if("tremolo"===c)d=new self.ze(b,...e);else if("ringmod"===c)d=new self.xe(b,...e);else if("distortion"===c)d=new self.se(b,...e);else if("compressor"===c)d=new self.pe(b,...e);else if("analyser"===c)d=new self.oe(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ka.get(h);l||(l=[],g.ka.set(h,l));d.Xd=l.length;d.kd=
h;l.push(d);Bb(g,h)}Cb(b)}
async function Db(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Fa()&&1===c||!e.Fa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.pc=a.timeScale;b.Tc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.za=a.isSilent;b.m.Sb(b.za);b.ec=a.masterVolume;b.Xa.gain.value=
b.ec;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Ab(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Eb(b,f,c)));Q(b)}
async function Fb(b,a){try{const c=b.g.suspend(a.time);b.Wd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.qb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Gb(d)),b.Wd=!0);await c}catch(c){Gb(c)}}
function ob(b){b.Yb||(b.Wc=!1,window.addEventListener("pointerup",b.Ca,!0),window.addEventListener("touchend",b.Ca,!0),window.addEventListener("click",b.Ca,!0),window.addEventListener("keydown",b.Ca,!0),b.Yb=!0)}
async function M(b,a,c,d,e,f){for(var g of b.ja)if(g.mb()===c)return await Kb(g),g;if(f)return null;if(e&&(b.kc||b.Vd)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.Fa()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.je;e&&f&&(b.Vd=!0);c=!e||b.kc||f?new self.Ce(b,a,c,d,e,f):new self.Ae(b,a,c,d,e);b.ja.push(c);await Kb(c);b.be.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.be.add(a));return c}
function Lb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Mb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.ea()}function Bb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Nb(b,a))e=f,d=c,e=e.da||e.F||e.G,e.disconnect(),e.connect(d);b.Ma&&b.cd===a&&(b.Ma.disconnect(),b.Ma.connect(c))}
function*Nb(b,a){if(a)for(const c of b.H)Lb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Pb(b,a,c){return c?b.m.lf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Qb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*P(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Lb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function rb(b,a,c,d,e,f){for(const g of b.H)if(g.mb()===c&&(g.tc()||f))return g.oa=e,g;a=await M(b,a,c,d,f);e="html5"===a.Pc?new self.Be(a.u,a,e):new self.De(a.u,a,e);b.H.push(e);return e}
function qb(b,a){a=a.join(" ");let c=b.Ib.get(a);if(!c){let d=null;c={rd:0,promise:new Promise(e=>d=e),resolve:d};b.Ib.set(a,c)}c.rd++}function vb(b,a){return(b=b.Ib.get((0===a.length?b.$d:a).join(" ")))?b.promise:Promise.resolve()}function Q(b){if(0<b.Va.size)v(b);else for(const a of b.H)if(!a.I&&!a.O()){v(b);break}}function Rb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Cb(b){b.Zc||(b.Zc=!0,Promise.resolve().then(()=>Sb(b)))}
function Sb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.lb());m(b,"fxstate",{fxstate:a});b.Zc=!1}
async function Eb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await rb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(N(b,!0),e=b.F,f=d.pos,b.cb[0]=f[0],b.cb[1]=f[1],b.cb[2]=f[2],f=d.orient,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],e.setPosition(...b.cb),e.setOrientation(...b.bb),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):N(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?O(b,!1):(O(b,!0),tb(b,d));c.Play(k,l,p,0);a.isPlaying||c.pb();c.Kc(a)}}}function Gb(b){console.error("[Audio] Offline rendering error: ",b)}
self.kb=class extends self.Ob{constructor(b){super(b,"audio");this.Xa=this.g=null;this.Yb=this.Wc=!1;this.Ca=()=>{if(!this.Wc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Yb&&(this.Wc=!0,window.removeEventListener("pointerup",this.Ca,!0),window.removeEventListener("touchend",this.Ca,!0),window.removeEventListener("click",this.Ca,!0),window.removeEventListener("keydown",
this.Ca,!0),this.Yb=!1)}};this.ja=[];this.H=[];this.R=null;this.$d=[];this.be=new Set;this.ae=-1;this.Ib=new Map;this.ec=1;this.za=!1;this.md=0;this.pc=1;this.Tc=0;this.de="HRTF";this.Pd="inverse";this.ee=600;this.ce=1E4;this.ge=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Vd=this.kc=!1;this.je=this.m.Ie();this.ka=new Map;this.Va=new Set;this.Wd=this.Zc=!1;this.cd="";this.Ma=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ma&&this.Ma.disconnect();this.cd=c.toLowerCase();this.Ma=this.g.createMediaStreamSource(a);
this.Ma.connect(Mb(this,this.cd))};this.Xb=null;self.C3Audio_GetOutputStream=()=>{this.Xb||(this.Xb=this.g.createMediaStreamDestination(),this.Xa.connect(this.Xb));return this.Xb.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>nb(this,a)],["play",a=>pb(this,a)],["stop",a=>{a=a.tags;for(const c of P(this,a))c.Ga()}],["stop-all",()=>{for(const a of this.H)a.Ga()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of P(this,c))a?d.pb():d.Rb();Q(this)}],["set-volume",
a=>{const c=a.tags;a=a.vol;for(const d of P(this,c))R(d,a)}],["fade-volume",a=>ub(this,a)],["set-master-volume",a=>{this.ec=a.vol;this.Xa.gain.value=this.ec}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of P(this,c))Tb(d,a)}],["set-silent",a=>{this.za=a.isSilent;this.m.Sb(this.za);for(const c of this.H)c.Vb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of P(this,c))d.Cc(a)}],["set-playback-rate",a=>wb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of P(this,
c))O(d,!0),tb(d,a)}],["seek",a=>xb(this,a)],["preload",a=>yb(this,a)],["unload",a=>zb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Dc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Ab(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Cb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ka.delete(a);Bb(this,a)}}],["tick",a=>{this.pc=a.timeScale;this.Tc=a.gameTime;this.ae=a.tickCount;if(0!==this.md)for(var c of this.H)c.Ia();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.sa===a&&sb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Db(this,a)],["offline-render-audio",a=>Fb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Xa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Qb(){return this.za}Ha(b){this.m.Ha(b)}Sa(b){this.m.Sa(b)}Ta(){for(var b of this.Va)b.Ta();
b=this.g.currentTime;for(var a of this.H)a.Ta(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.lb());m(this,"state",{tickCount:this.ae,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Va].map(c=>({tag:c.kd,index:c.Xd,peak:c.eb,rms:c.fe,binCount:c.l.frequencyBinCount,freqBins:c.Ud}))});0===a.length&&0===this.Va.size&&this.Zb&&(this.m.Id(this.ke),this.Zb=!1)}static Ne(b){return b*mb}static wd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Le(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.pa.xa(self.kb);"use strict";function Kb(b){b.cc||(b.cc=b.Jc());return b.cc}self.td=class{constructor(b,a,c,d,e){this.u=b;this.rf=a;this.Na=c;this.T=d;this.nf=e;this.Pc="";this.cc=null}j(){this.cc=this.u=null}Jc(){}V(){return this.u.V()}yc(){return this.rf}mb(){return this.Na}wc(){return this.T}Fa(){return this.nf}fa(){}};"use strict";
self.Ae=class extends self.td{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Pc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Db=this.Eb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Hb=this.V().createGain();this.Gb=null;this.L.addEventListener("canplay",()=>{this.Eb&&(this.Eb(),this.Db=this.Eb=null);!this.Gb&&this.L&&(this.Gb=this.V().createMediaElementSource(this.L),this.Gb.connect(this.Hb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Na}' error: `,f);this.Db&&(this.Db(f),this.Db=this.Eb=null)})}j(){Qb(this.u,this);this.Hb.disconnect();this.Hb=null;this.Gb.disconnect();this.Gb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Jc(){return new Promise((b,a)=>{this.Eb=b;this.Db=a;this.L.src=this.Na})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Ub(b){if(b.Ja)return b.Ja;var a=b.u.m;if("cordova"===a.A&&a.zd(b.Na)&&a.ac)b.Ja=await a.Nb(b.Na);else{a=await fetch(b.Na);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ja=await a.arrayBuffer()}}async function Vb(b){if(b.ia)return b.ia;b.ia=await Pb(b.u,b.Ja,b.qf);b.Ja=null}
self.Ce=class extends self.td{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Pc="webaudio";this.ia=this.Ja=null;this.qf=!!f}j(){Qb(this.u,this);this.ia=this.Ja=null;super.j()}async Jc(){try{await Ub(this),await Vb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Na}': `,b)}}fa(){return this.ia?this.ia.duration:0}};"use strict";let Wb=0;
function N(b,a){a=!!a;b.Ab!==a&&(b.Ab=a,b.Ab?(O(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.de,b.F.distanceModel=b.u.Pd,b.F.refDistance=b.u.ee,b.F.maxDistance=b.u.ce,b.F.rolloffFactor=b.u.ge),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function O(b,a){a=!!a;b.bc!==a&&(b.bc=a,b.bc?(N(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.ea())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.ea())))}function tb(b,a){b.bc&&b.jd!==a&&(b.da.pan.value=a,b.jd=a)}function R(b,a){b.Oa=a;b.G.gain.cancelScheduledValues(0);b.Za=-1;b.G.gain.value=b.zc()}function Tb(b,a){a=!!a;b.ya!==a&&(b.ya=a,b.Vb())}
function sb(b,a,c,d,e){if(b.Ab){var f=b.cb,g=b.bb,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function S(b){return b.$c?b.u.Tc:performance.now()/1E3}
self.ud=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Wb=Wb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.Ab=!1;this.cb=[0,0,0];this.bb=[0,0,0];this.ua=[0,0,0];this.da=null;this.bc=!1;this.jd=0;this.I=!0;this.Y=this.va=this.J=!1;this.Oa=1;this.ya=!1;this.ma=1;b=this.u.md;this.$c=1===b&&!this.Fa()||2===b;this.Za=this.sa=-1;this.ie=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return Mb(this.u,0<this.oa.length?this.oa[0]:"")}yc(){return this.P.yc()}mb(){return this.P.mb()}wc(){return this.P.wc()}Fa(){return this.P.Fa()}O(){}tc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Qa(){}fa(){return this.P.fa()}Play(){}Ga(){}pb(){}Rb(){}Ta(b){-1!==this.Za&&b>=this.Za&&(this.Za=-1,this.ie&&this.Ga(),Rb(this.u,"fade-ended",this.oa,this.Wb))}zc(){const b=this.Oa;return isFinite(b)?b:0}Qb(){return this.u.Qb()}Vb(){}Cc(){}Ia(){}Bc(){}Dc(){}Ac(){}lb(){var b=
this.Wb,a=this.oa,c=this.fa(),d=-1===this.Za?this.Oa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.cb,orient:this.bb,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Qa(),playbackRate:this.ma,uid:this.sa,bufferOriginalUrl:this.yc(),bufferUrl:"",bufferType:this.wc(),isMusic:this.Fa(),isLooping:this.Y,isMuted:this.ya,resumePosition:this.Ac(),pan:f,stereoPan:this.da?
this.jd:null}}Kc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ia());Tb(this,b.isMuted)}};"use strict";
self.Be=class extends self.ud{constructor(b,a,c){super(b,a,c);this.P.Hb.connect(this.G);this.P.onended=()=>this.Lc()}j(){this.Ga();this.P.Hb.disconnect();super.j()}W(){return this.P.W()}Lc(){this.I=!0;this.sa=-1;Rb(this.u,"ended",this.oa,this.Wb)}O(){return this.W().ended}tc(){return this.I?!0:this.O()}Qa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);R(this,a);this.ya=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.mb()}' to position '${c}': `,e)}this.u.Ha(d);this.J=this.I=!1;this.Y=b;this.ma=1}Ga(){const b=this.W();b.paused||b.pause();this.u.Sa(b);this.I=!0;this.J=!1;this.sa=-1}pb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Sa(b);this.J=!0}}Rb(){!this.J||this.I||this.O()||(this.u.Ha(this.W()),this.J=!1)}Vb(){this.W().muted=this.ya||this.Qb()}Cc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ia(){let b=this.ma;this.$c&&(b*=this.u.pc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Bc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Ac(){return this.Qa()}Dc(b){b?this.IsPlaying()?(this.W().pause(),this.va=!0):this.va=!1:this.va&&(this.u.Ha(this.W()),this.va=!1)}};"use strict";
function T(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.sb=null}
self.De=class extends self.ud{constructor(b,a,c){super(b,a,c);this.s=null;this.hc=d=>this.Lc(d);this.Vc=!0;this.sb=null;this.S=this.jc=this.lc=0;this.ed=1}j(){this.Ga();T(this);this.hc=null;super.j()}Lc(b){this.J||this.va||b.target!==this.sb||(this.I=this.Vc=!0,this.sa=-1,T(this),Rb(this.u,"ended",this.oa,this.Wb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Vc}tc(){return!this.s||this.I?!0:this.O()}Qa(){let b;b=this.J?this.S:this.jc+(S(this)-this.lc)*this.ma;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.ya=!1;this.ed=1;R(this,a);T(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ia;this.s.connect(this.G);this.sb=this.s;this.s.onended=this.hc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Vc=!1;this.Y=b;this.ma=1;this.lc=S(this);this.jc=c}Ga(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.sa=-1}pb(){this.J||this.I||this.O()||(this.S=this.Qa(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Rb(){!this.J||this.I||this.O()||(T(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.sb=this.s,this.s.onended=this.hc,this.s.loop=this.Y,R(this,this.Oa),this.Ia(),this.s.start(0,this.S),this.lc=S(this),this.jc=this.S,this.J=!1)}zc(){return super.zc()*this.ed}Vb(){this.ed=this.ya||this.Qb()?0:1;R(this,this.Oa)}Cc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ia(){let b=this.ma;this.$c&&(b*=this.u.pc);this.s&&(this.s.playbackRate.value=b)}Bc(b){this.I||this.O()||(this.J?this.S=b:(this.pb(),
this.S=b,this.Rb()))}Ac(){return this.S}Dc(b){b?this.IsPlaying()?(this.va=!0,this.S=this.Qa(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.va=!1:this.va&&(T(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.sb=this.s,this.s.onended=this.hc,this.s.loop=this.Y,R(this,this.Oa),this.Ia(),this.s.start(0,this.S),this.lc=S(this),this.jc=this.S,this.va=!1)}Kc(b){super.Kc(b);this.S=b.resumePosition}};"use strict";function U(b){return b.g.createGain()}
function V(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class W{constructor(b){this.u=b;this.g=b.V();this.Xd=-1;this.T=this.kd="";this.o=null}j(){this.g=null}N(){}U(){}lb(){return{type:this.T,tag:this.kd,params:this.o}}}
self.te=class extends W{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.v=U(this);this.i=U(this);this.i.gain.value=g;this.h=U(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;V(this,this.i.gain,a,c,d);V(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;V(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;V(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;V(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,V(this,this.D.gain,a,c,d)}}};
self.re=class extends W{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.v=U(this);this.i=U(this);this.i.gain.value=d;this.h=U(this);this.h.gain.value=1-d;this.Fb=U(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.wb=U(this);this.wb.gain.value=c;this.v.connect(this.Fb);this.v.connect(this.h);this.Fb.connect(this.i);this.Fb.connect(this.X);this.X.connect(this.wb);this.wb.connect(this.Fb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Fb.disconnect();
this.X.disconnect();this.wb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.kb.wd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;V(this,this.i.gain,a,c,d);V(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);V(this,this.wb.gain,e(a),c,d);break;case 5:this.o[0]=a,V(this,this.X.delayTime,a,c,d)}}};
self.qe=class extends W{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Od=this.Nd="";this.v=U(this);this.i=U(this);this.i.gain.value=d;this.h=U(this);this.h.gain.value=1-d;this.vb=this.g.createConvolver();this.vb.normalize=c;this.vb.buffer=a;this.v.connect(this.vb);this.v.connect(this.h);this.vb.connect(this.i)}j(){this.v.disconnect();this.vb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,V(this,this.i.gain,a,c,d),V(this,this.h.gain,1-a,c,d)}}lb(){const b=super.lb();b.bufferOriginalUrl=this.Nd;b.bufferUrl="";b.bufferType=this.Od;return b}};
self.ue=class extends W{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.v=U(this);this.h=U(this);this.h.gain.value=1-f/2;this.i=U(this);this.i.gain.value=f/2;this.yb=U(this);this.yb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=U(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.yb);this.yb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.yb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;V(this,this.i.gain,a/2,c,d);V(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;V(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;V(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,V(this,this.yb.gain,a/100,c,d)}}};
self.we=class extends W{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.v=U(this);this.h=U(this);this.h.gain.value=1-g/2;this.i=U(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=U(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;V(this,this.i.gain,a/2,c,d);V(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;V(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;V(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;V(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;V(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,V(this,this.C.frequency,a,c,d)}}};self.ve=class extends W{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=U(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.kb.wd;switch(b){case 4:this.o[0]=e(a),V(this,this.l.gain,e(a),c,d)}}};
self.ye=class extends W{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,V(this,this.l.pan,a,c,d)}}};
self.ze=class extends W{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=U(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=U(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;V(this,this.l.gain,1-a/2,c,d);V(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,V(this,this.C.frequency,a,c,d)}}};
self.xe=class extends W{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.v=U(this);this.i=U(this);this.i.gain.value=c;this.h=U(this);this.h.gain.value=1-c;this.Kb=U(this);this.Kb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Kb.gain);this.C.start(0);this.v.connect(this.Kb);this.v.connect(this.h);this.Kb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Kb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;V(this,this.i.gain,a,c,d);V(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,V(this,this.C.frequency,a,c,d)}}};
self.se=class extends W{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.v=U(this);this.nc=U(this);this.mc=U(this);b=d;.01>b&&(b=.01);this.nc.gain.value=b;this.mc.gain.value=Math.pow(1/b,.6)*e;this.i=U(this);this.i.gain.value=f;this.h=U(this);this.h.gain.value=1-f;this.qc=this.g.createWaveShaper();this.Qc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Qc[32768+e]=f,this.Qc[32768-
e-1]=-f;this.qc.curve=this.Qc;this.v.connect(this.nc);this.v.connect(this.h);this.nc.connect(this.qc);this.qc.connect(this.mc);this.mc.connect(this.i)}j(){this.v.disconnect();this.nc.disconnect();this.qc.disconnect();this.mc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,V(this,this.i.gain,a,c,d),V(this,this.h.gain,
1-a,c,d)}}};self.pe=class extends W{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.oe=class extends W{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Ud=new Float32Array(this.l.frequencyBinCount);this.he=new Uint8Array(a);this.fe=this.eb=0;b=this.u;b.Va.add(this);Q(b)}j(){this.u.Va.delete(this);this.l.disconnect();super.j()}Ta(){this.l.getFloatFrequencyData(this.Ud);this.l.getByteTimeDomainData(this.he);const b=this.l.fftSize;let a=this.eb=0;for(var c=0;c<b;++c){let d=(this.he[c]-
128)/128;0>d&&(d=-d);this.eb<d&&(this.eb=d);a+=d*d}c=self.kb.Le;this.eb=c(this.eb);this.fe=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";function Xb(b,a,c){Yb(b,a,URL.createObjectURL(new Blob([c.html],{type:"text/html"})));b.$b=!0}function Yb(b,a,c){a.src&&a.src.startsWith("blob:")&&b.$b&&URL.revokeObjectURL(a.src);a.src=c}
self.pa.xa(class extends self.Ea{constructor(b){super(b,"iframe");this.$b=!1;x(this,"navigate-url",(a,c)=>{Yb(this,a,c.url);this.$b=!1});x(this,"display-html",(a,c)=>Xb(this,a,c))}Pa(b,a){b=document.createElement("iframe");b.style.position="absolute";b.style.border="none";a.isVisible||(b.style.display="none");a.id&&(b.id=a.id);a.allow&&(b.setAttribute("allow",a.allow),a.allow.includes("fullscreen")&&b.setAttribute("allowfullscreen",""));a.enableSandbox&&b.setAttribute("sandbox",a.sandbox);a.url?b.src=
a.url:a.html&&Xb(this,b,a);return b}ga(){}xd(b){Yb(this,b,"");this.$b=!1}});"use strict";function X(b){b.stopPropagation()}
self.pa.xa(class extends self.Ea{constructor(b){super(b,"file-chooser");x(this,"click",a=>{a.click()});x(this,"clear",a=>{a.value=""})}Pa(b,a){const c=document.createElement("input");c.type="file";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",X);c.addEventListener("pointermove",X);c.addEventListener("pointerrawupdate",X);c.addEventListener("pointerup",X);c.addEventListener("mousedown",X);c.addEventListener("mouseup",X);c.addEventListener("contextmenu",
d=>d.preventDefault());c.addEventListener("change",()=>w(this,"change",b,{files:Array.from(c.files)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.ga(c,a);return c}ga(b,a){b.setAttribute("accept",a.accept);a.isMultiSelect?b.setAttribute("multiple",""):b.removeAttribute("multiple")}});"use strict";function Y(b){b.stopPropagation()}
self.pa.xa(class extends self.Ea{constructor(b){super(b,"sliderbar")}Pa(b,a){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Y);c.addEventListener("pointermove",Y);c.addEventListener("pointerrawupdate",Y);c.addEventListener("pointerup",Y);c.addEventListener("mousedown",Y);c.addEventListener("mouseup",Y);c.addEventListener("keydown",Y);c.addEventListener("keyup",Y);c.addEventListener("contextmenu",
d=>d.preventDefault());c.addEventListener("click",()=>z(this,b));c.addEventListener("change",()=>w(this,"change",b,{value:parseFloat(c.value)}));c.addEventListener("input",()=>w(this,"input",b,{value:parseFloat(c.value)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.ga(c,a);return c}ga(b,a){b.max=a.max;b.min=a.min;b.step=a.step;b.value=a.value;b.disabled=!a.isEnabled;b.title=a.title}});"use strict";function Z(b){b.stopPropagation()}
self.pa.xa(class extends self.Ea{constructor(b){super(b,"progress-bar")}Pa(b,a){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("click",()=>z(this,b));a.id&&(c.id=a.id);a.className&&(c.className=
a.className);this.ga(c,a);return c}ga(b,a){b.title=a.title;const c=a.value;a=a.max;0<a&&0<=c?(b.max=a,b.value=c):(b.removeAttribute("value"),b.removeAttribute("max"))}});
